from __future__ import annotations


POSITIVE_TOKENS = (
    "excelente",
    "genial",
    "perfecto",
    "perfecta",
    "bueno",
    "buena",
    "increible",
    "increíble",
    "maravilloso",
    "maravillosa",
    "amable",
    "recomendable",
    "volveremos",
    "great",
    "excellent",
    "amazing",
    "friendly",
    "recommend",
)

NEGATIVE_TOKENS = (
    "malo",
    "mala",
    "fatal",
    "horrible",
    "terrible",
    "pésimo",
    "pesimo",
    "caro",
    "cara",
    "frio",
    "fría",
    "fria",
    "lento",
    "lenta",
    "sucio",
    "sucia",
    "decepcion",
    "decepción",
    "never",
    "bad",
    "awful",
    "slow",
    "dirty",
    "disappoint",
)

EXPECTATION_TOKENS = (
    "esperaba",
    "esperabamos",
    "esperábamos",
    "deberia",
    "debería",
    "por este precio",
    "mejorable",
    "decepcion",
    "decepción",
    "could be better",
    "expected",
)

IMPROVEMENT_TOKENS = (
    "deberian",
    "deberían",
    "podrian",
    "podrían",
    "sugiero",
    "recomiendo mejorar",
    "mejorar",
    "seria mejor",
    "sería mejor",
    "would improve",
    "should",
)

AGGRESSIVE_TOKENS = (
    "vergüenza",
    "verguenza",
    "estafa",
    "nunca",
    "jamas",
    "jamás",
    "horrible",
    "asqueroso",
    "desastre",
    "inaceptable",
    "impresentable",
    "worst",
    "scam",
    "unacceptable",
)

THEME_KEYWORDS: dict[str, tuple[str, ...]] = {
    "servicio": (
        "servicio",
        "camarero",
        "camarera",
        "atencion",
        "atención",
        "staff",
        "trato",
    ),
    "tiempo_espera": (
        "espera",
        "tardar",
        "tardaron",
        "lento",
        "lenta",
        "cola",
        "wait",
    ),
    "precio_valor": (
        "precio",
        "caro",
        "cara",
        "calidad precio",
        "quality price",
        "coste",
        "cost",
    ),
    "calidad_comida": (
        "comida",
        "plato",
        "sabor",
        "frio",
        "fría",
        "fria",
        "caliente",
        "food",
        "taste",
    ),
    "limpieza": (
        "limpio",
        "limpia",
        "sucio",
        "sucia",
        "higiene",
        "baño",
        "bano",
        "clean",
        "dirty",
    ),
    "ambiente_ruido": (
        "ruido",
        "ruidoso",
        "ruidosa",
        "ambiente",
        "musica",
        "música",
        "noise",
        "loud",
    ),
    "gestion_reservas": (
        "reserva",
        "booking",
        "cancelacion",
        "cancelación",
        "mesa",
        "confirmacion",
        "confirmación",
    ),
}

GENERIC_COMMENT_PROBLEM = "Comentario general no específico"
POSITIVE_COMMENT_PROBLEM = "Comentario positivo no específico"
NEGATIVE_COMMENT_PROBLEM = "Comentario negativo no específico"
NO_COMMENT_HIGH_PROBLEM = "Valoración alta sin comentarios"
NO_COMMENT_MEDIUM_PROBLEM = "Valoración media sin comentarios"
NO_COMMENT_LOW_PROBLEM = "Valoración baja sin comentarios"

STOPWORDS = {
    "de",
    "la",
    "el",
    "y",
    "a",
    "en",
    "que",
    "por",
    "con",
    "para",
    "los",
    "las",
    "un",
    "una",
    "muy",
    "del",
    "al",
    "se",
    "es",
    "lo",
    "le",
    "me",
    "mi",
    "no",
    "si",
    "sin",
    "como",
    "todo",
    "esta",
    "está",
    "the",
    "and",
    "for",
    "with",
    "was",
    "were",
    "this",
    "that",
    "from",
    "our",
    "very",
}
